/** Official titles for CFR parts in the database. Key format: "TITLE-PART" (e.g., "46-1", "33-160"). */
const CFR_PART_TITLES: Record<string, string> = {
  // 33 CFR
  "33-160": "PORTS AND WATERWAYS SAFETY—GENERAL",
  "33-164": "NAVIGATION SAFETY REGULATIONS",
  // 46 CFR Subchapter A — Procedures Applicable to the Public
  "46-1": "ORGANIZATION, GENERAL COURSE AND METHODS GOVERNING MARINE SAFETY FUNCTIONS",
  "46-2": "VESSEL INSPECTIONS",
  "46-3": "DESIGNATION OF OCEANOGRAPHIC RESEARCH VESSELS",
  "46-4": "MARINE CASUALTIES AND INVESTIGATIONS",
  "46-5": "MARINE INVESTIGATION REGULATIONS—PERSONNEL ACTION",
  "46-6": "WAIVERS OF NAVIGATION AND VESSEL INSPECTION LAWS AND REGULATIONS",
  "46-7": "BOUNDARY LINES",
  "46-8": "VESSEL INSPECTION ALTERNATIVES",
  "46-9": "EXTRA COMPENSATION FOR OVERTIME SERVICES",
  // 46 CFR Subchapter B — Merchant Marine Officers and Seamen
  "46-10": "MERCHANT MARINER CREDENTIAL",
  "46-11": "REQUIREMENTS FOR OFFICER ENDORSEMENTS",
  "46-12": "REQUIREMENTS FOR RATING ENDORSEMENTS",
  "46-13": "CERTIFICATION OF TANKERMEN",
  "46-14": "SHIPMENT AND DISCHARGE OF MERCHANT MARINERS",
  "46-15": "MANNING REQUIREMENTS",
  "46-16": "CHEMICAL TESTING",
  // 46 CFR Subchapter C — Uninspected Vessels
  "46-24": "GENERAL PROVISIONS",
  "46-25": "REQUIREMENTS",
  "46-26": "CONDITIONS UNDER WHICH VESSELS MUST OBTAIN CERTIFICATES",
  "46-27": "TOWING VESSELS",
  "46-28": "REQUIREMENTS FOR COMMERCIAL FISHING INDUSTRY VESSELS",
  // 46 CFR Subchapter D — Tank Vessels
  "46-30": "GENERAL PROVISIONS",
  "46-31": "INSPECTION AND CERTIFICATION",
  "46-32": "SPECIAL EQUIPMENT, MACHINERY, AND HULL REQUIREMENTS",
  "46-34": "FIRE FIGHTING EQUIPMENT",
  "46-35": "OPERATIONS",
  "46-36": "ELEVATED TEMPERATURE CARGOES",
  "46-38": "LIQUEFIED FLAMMABLE GASES",
  "46-39": "VAPOR CONTROL SYSTEMS",
  // 46 CFR Subchapter E — Load Lines
  "46-42": "DOMESTIC AND FOREIGN VOYAGES BY SEA",
  "46-44": "SPECIAL SERVICE LIMITED DOMESTIC VOYAGES",
  "46-45": "GREAT LAKES LOAD LINES",
  "46-46": "SUBDIVISION LOAD LINES FOR PASSENGER VESSELS",
  "46-47": "COMBINATION LOAD LINES",
  // 46 CFR Subchapter F — Marine Engineering
  "46-50": "GENERAL PROVISIONS",
  "46-52": "POWER BOILERS",
  "46-53": "HEATING BOILERS",
  "46-54": "PRESSURE VESSELS",
  "46-56": "PIPING SYSTEMS AND APPURTENANCES",
  "46-57": "WELDING AND BRAZING",
  "46-58": "MAIN AND AUXILIARY MACHINERY AND RELATED SYSTEMS",
  "46-59": "REPAIRS TO BOILERS, PRESSURE VESSELS AND APPURTENANCES",
  "46-61": "PERIODIC TESTS AND INSPECTIONS",
  "46-62": "VITAL SYSTEM AUTOMATION",
  "46-63": "AUTOMATIC AUXILIARY BOILERS",
  "46-64": "MARINE PORTABLE TANKS AND CARGO HANDLING SYSTEMS",
  // 46 CFR Subchapter G — Documentation and Measurement of Vessels
  "46-67": "DOCUMENTATION OF VESSELS",
  "46-68": "DOCUMENTATION OF VESSELS: EXCEPTIONS TO COASTWISE QUALIFICATION",
  "46-69": "MEASUREMENT OF VESSELS",
  // 46 CFR Subchapter H — Passenger Vessels
  "46-70": "GENERAL PROVISIONS",
  "46-71": "INSPECTION AND CERTIFICATION",
  "46-72": "CONSTRUCTION AND ARRANGEMENT",
  "46-76": "FIRE PROTECTION EQUIPMENT",
  "46-77": "VESSEL CONTROL AND MISCELLANEOUS SYSTEMS AND EQUIPMENT",
  "46-78": "OPERATIONS",
  "46-80": "DISCLOSURE OF SAFETY STANDARDS AND COUNTRY OF REGISTRY",
  // 46 CFR Subchapter I — Cargo and Miscellaneous Vessels
  "46-90": "GENERAL PROVISIONS",
  "46-91": "INSPECTION AND CERTIFICATION",
  "46-92": "CONSTRUCTION AND ARRANGEMENT",
  "46-93": "STABILITY",
  "46-95": "FIRE PROTECTION EQUIPMENT",
  "46-96": "VESSEL CONTROL AND MISCELLANEOUS SYSTEMS AND EQUIPMENT",
  "46-97": "OPERATIONS",
  "46-98": "SPECIAL CONSTRUCTION, ARRANGEMENT, AND OTHER PROVISIONS FOR CERTAIN DANGEROUS CARGOES IN BULK",
  "46-105": "COMMERCIAL FISHING VESSELS DISPENSING PETROLEUM PRODUCTS",
  "46-106": "REQUIREMENTS FOR NONQUALIFIED VESSELS THAT PERFORM CERTAIN AQUACULTURE SUPPORT OPERATIONS",
  // 46 CFR Subchapter I-A — Mobile Offshore Drilling Units
  "46-107": "INSPECTION AND CERTIFICATION OF VESSELS",
  "46-108": "DESIGN AND EQUIPMENT",
  "46-109": "OPERATIONS",
  // 46 CFR Subchapter J — Electrical Engineering
  "46-110": "GENERAL PROVISIONS",
  "46-111": "ELECTRIC SYSTEMS—GENERAL REQUIREMENTS",
  "46-112": "EMERGENCY LIGHTING AND POWER SYSTEMS",
  "46-113": "COMMUNICATION AND ALARM SYSTEMS AND EQUIPMENT",
  // 46 CFR Subchapter K — Small Passenger Vessels (Under 100 GT)
  "46-114": "GENERAL PROVISIONS",
  "46-115": "INSPECTION AND CERTIFICATION",
  "46-116": "CONSTRUCTION AND ARRANGEMENT",
  "46-117": "LIFESAVING EQUIPMENT AND ARRANGEMENTS",
  "46-118": "FIRE PROTECTION EQUIPMENT",
  "46-119": "MACHINERY INSTALLATION",
  "46-120": "ELECTRICAL INSTALLATION",
  "46-121": "VESSEL CONTROL AND MISCELLANEOUS SYSTEMS AND EQUIPMENT",
  "46-122": "OPERATIONS",
  // 46 CFR Subchapter L — Offshore Supply Vessels
  "46-125": "GENERAL",
  "46-126": "INSPECTION AND CERTIFICATION",
  "46-127": "CONSTRUCTION AND ARRANGEMENTS",
  "46-128": "MARINE ENGINEERING: EQUIPMENT AND SYSTEMS",
  "46-129": "ELECTRICAL INSTALLATIONS",
  "46-130": "VESSEL CONTROL, AND MISCELLANEOUS EQUIPMENT AND SYSTEMS",
  "46-131": "OPERATIONS",
  "46-132": "FIRE PROTECTION EQUIPMENT",
  "46-133": "LIFESAVING",
  "46-134": "ADDED PROVISIONS FOR LIFTBOATS",
  // 46 CFR Subchapter M — Towing Vessels
  "46-136": "CERTIFICATION",
  "46-137": "VESSEL COMPLIANCE",
  "46-138": "TOWING SAFETY MANAGEMENT SYSTEMS",
  "46-139": "THIRD-PARTY ORGANIZATIONS",
  "46-140": "OPERATIONS",
  "46-141": "LIFESAVING",
  "46-142": "FIRE PROTECTION",
  "46-143": "MACHINERY AND ELECTRICAL SYSTEMS AND EQUIPMENT",
  "46-144": "CONSTRUCTION AND ARRANGEMENT",
  // 46 CFR Subchapter N — Dangerous Cargoes
  "46-147": "HAZARDOUS SHIPS' STORES",
  "46-148": "CARRIAGE OF BULK SOLID MATERIALS THAT REQUIRE SPECIAL HANDLING",
  "46-150": "COMPATIBILITY OF CARGOES",
  "46-151": "BARGES CARRYING BULK LIQUID HAZARDOUS MATERIAL CARGOES",
  "46-153": "SHIPS CARRYING BULK LIQUID, LIQUEFIED GAS, OR COMPRESSED GAS HAZARDOUS MATERIALS",
  "46-154": "SAFETY STANDARDS FOR SELF-PROPELLED VESSELS CARRYING BULK LIQUEFIED GASES",
  // 46 CFR Subchapter Q — Equipment, Construction, and Materials
  "46-159": "APPROVAL OF EQUIPMENT AND MATERIALS",
  "46-160": "LIFESAVING EQUIPMENT",
  "46-161": "ELECTRICAL EQUIPMENT",
  "46-162": "ENGINEERING EQUIPMENT",
  "46-163": "CONSTRUCTION",
  "46-164": "MATERIALS",
  "46-166": "DESIGNATION AND APPROVAL OF NAUTICAL SCHOOL SHIPS",
  // 46 CFR Subchapter R — Nautical Schools
  "46-167": "PUBLIC NAUTICAL SCHOOL SHIPS",
  "46-168": "CIVILIAN NAUTICAL SCHOOL VESSELS",
  "46-169": "SAILING SCHOOL VESSELS",
  // 46 CFR Subchapter S — Subdivision and Stability
  "46-170": "STABILITY REQUIREMENTS FOR ALL INSPECTED VESSELS",
  "46-171": "SPECIAL RULES PERTAINING TO VESSELS CARRYING PASSENGERS",
  "46-172": "SPECIAL RULES PERTAINING TO BULK CARGOES",
  "46-173": "SPECIAL RULES PERTAINING TO VESSEL USE",
  "46-174": "SPECIAL RULES PERTAINING TO SPECIFIC VESSEL TYPES",
  // 46 CFR Subchapter T — Small Passenger Vessels (Under 100 GT)
  "46-175": "GENERAL PROVISIONS",
  "46-176": "INSPECTION AND CERTIFICATION",
  "46-177": "CONSTRUCTION AND ARRANGEMENT",
  "46-178": "INTACT STABILITY AND SEAWORTHINESS",
  "46-179": "SUBDIVISION, DAMAGE STABILITY, AND WATERTIGHT INTEGRITY",
  "46-180": "LIFESAVING EQUIPMENT AND ARRANGEMENTS",
  "46-181": "FIRE PROTECTION EQUIPMENT",
  "46-182": "MACHINERY INSTALLATION",
  "46-183": "ELECTRICAL INSTALLATION",
  "46-184": "VESSEL CONTROL AND MISCELLANEOUS SYSTEMS AND EQUIPMENT",
  "46-185": "OPERATIONS",
  // 46 CFR Subchapter U — Oceanographic Vessels
  "46-188": "GENERAL PROVISIONS",
  "46-189": "INSPECTION AND CERTIFICATION",
  "46-190": "CONSTRUCTION AND ARRANGEMENT",
  "46-193": "FIRE PROTECTION EQUIPMENT",
  "46-194": "HANDLING, USE, AND CONTROL OF EXPLOSIVES AND OTHER HAZARDOUS MATERIALS",
  "46-195": "VESSEL CONTROL AND MISCELLANEOUS SYSTEMS AND EQUIPMENT",
  "46-196": "OPERATIONS",
  // 46 CFR Subchapter V — Marine Occupational Safety and Health Standards
  "46-197": "GENERAL PROVISIONS",
  "46-199": "LIFESAVING SYSTEMS FOR CERTAIN INSPECTED VESSELS",
};

/** Extract CFR title-part key from a document_id like "cfr/46-CFR-Part-10" or "cfr/33-CFR-part160". */
export function getCfrPartKey(documentId: string): string | null {
  // Handle "cfr/46-CFR-Part-10" format
  const m46 = documentId.match(/cfr\/(\d+)-CFR-Part-(\d+)$/i);
  if (m46) return `${m46[1]}-${m46[2]}`;
  // Handle "cfr/33-CFR-part160" format (no dash before number)
  const m33 = documentId.match(/cfr\/(\d+)-CFR-part(\d+)$/i);
  if (m33) return `${m33[1]}-${m33[2]}`;
  return null;
}

/** Get the official title for a CFR part given its document_id. */
export function getCfrPartTitle(documentId: string): string | null {
  const key = getCfrPartKey(documentId);
  return key ? CFR_PART_TITLES[key] ?? null : null;
}

/** Extract the numeric part number for sorting. */
export function getCfrSortNumber(documentId: string): number {
  const key = getCfrPartKey(documentId);
  if (!key) return 0;
  const parts = key.split("-");
  // Sort by CFR title (33 before 46) then by part number
  return parseInt(parts[0]) * 10000 + parseInt(parts[1]);
}

export default CFR_PART_TITLES;
